# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Provose"

email: "engineering@neocrym.com"

tagline: "Provose is the easiest way to manage your Amazon Web Services infrastructure."

description: >- # this means to ignore newlines until "baseurl:"
  Provose is a Terraform super-module. You tell it what types of databases
  and containers you want to run on Amazon Web Services (AWS), and it
  automatically provisions certificates, security groups, IAM policies,
  and more.

logo: "/assets/images/1x/logo-black-on-transparent-1x.png"

defaults:
  - scope:
      path: ""
    values:
      image: "/assets/images/1x/twitter-facebook-preview-card-1x.png"


image: "/assets/images/1x/twitter-facebook-preview-card-1x.png"

footer_content: 'Copyright &copy; 2020-2021 <a href="https://neocrym.com">Neocrym Records Inc</a>. Distributed via an <a href="https://github.com/provose/provose/blob/master/LICENSE">MIT license</a>. <a href="/privacy/">Privacy Policy</a>.'

destination: docs

permalink: pretty

baseurl: "" # the subpath of your site, e.g. /blog

url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: neocrym

twitter:
  username: neocrym
  card: summary_large_image
  
github_username: neocrym

color_scheme: provose

social:
  name: Neocrym Records Inc.
  links:
    - https://twitter.com/neocrym
    - https://www.facebook.com/neocrym
    - https://www.linkedin.com/company/neocrym
    - https://github.com/provose


latest_provose_version: v3.0

# Build settings
remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-sitemap
  - jekyll-admin
  - jekyll-seo-tag

# Enable search: https://pmarsceill.github.io/just-the-docs/docs/search/
search_enabled: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .git
  - .jekyll-cache/
  - .sass-cache/
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - build-all-versions.sh
  - cache
  - clone-docs-dir.sh
  - docker-compose.yml
  - gemfiles/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

aux_links:
  "Provose on GitHub":
    - "https://github.com/provose/provose/"
  "Neocrym.com":
    - "https://www.neocrym.com"

ga_tracking: UA-156547622-4
