version: "3.1"
services:
  jekyll:
    build: .
    image: jekyll
    restart: always
    ports:
      - "4001:4000"
    volumes:
      - ".:/srv/jekyll"
    entrypoint: "bundle exec jekyll serve --incremental --host=0.0.0.0"
